spring:
  application:
    name: hr-config-server
  server:
    port: 8888
  cloud:
    config:
      server:
        git:
          uri: git@github.com:vinisolon/ms-course-configs.git
#          ignore-local-ssh-settings: true
          private-key-file: C:\Users\vinicius.araujo\.ssh\id_rsa